server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: hr-attendance-saas

  profiles:
    default: test

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers

  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

security:
  jwt:
    secret: change-this-secret-key
    expiration: 86400000